import sys
from pathlib import Path

# Allow this script to run from the project root without installing the package.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import numpy as np

from src.indexer import build_faiss_index, save_faiss_index

EMB_PATH = Path("data/processed/embeddings.npy")
INDEX_PATH = Path("data/index/faiss.index")


def main():
    # Build the runtime FAISS index from normalized embeddings generated by embed_corpus.py.
    if not EMB_PATH.exists():
        raise FileNotFoundError("Missing embeddings.npy. Run scripts/embed_corpus.py first.")

    embeddings = np.load(EMB_PATH)
    index = build_faiss_index(embeddings, use_ip=True)
    save_faiss_index(index, INDEX_PATH)

    print(f"✅ Built FAISS index: {INDEX_PATH}")
    print(f"   ntotal={index.ntotal}, dim={index.d}")


if __name__ == "__main__":
    main()
